Repository openstack-k8s-operators/neutron-operator, pull requests merged in 2024-02, with the labels that each got.

#288 [go.mod]Bump from v0.3.0 to pseudoversion
  go.mod
  go.sum
Labels: approved, lgtm

#293 Drop Debug fields
  README.md
  api/bases/neutron.openstack.org_neutronapis.yaml
  api/v1beta1/neutronapi_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/neutron.openstack.org_neutronapis.yaml
  config/samples/neutron_v1beta1_neutronapi.yaml
  config/samples/neutron_v1beta1_neutronapi_tls.yaml
  pkg/neutronapi/deployment.go
  test/functional/neutronapi_controller_test.go
  test/kuttl/common/assert_sample_deployment.yaml
Labels: approved, lgtm

#291 Build neutron-operator image in the FIPS compatible way
  .prow_ci.env
  Dockerfile
  Makefile
Labels: approved, lgtm

#297 Hardcode neutron database and database-account CR names to `neutron`
  config/rbac/role.yaml
  controllers/neutronapi_controller.go
  go.mod
  go.sum
  test/functional/neutronapi_controller_test.go
  test/kuttl/common/assert_sample_deployment.yaml
  test/kuttl/tests/neutron_tls/01-assert.yaml
Labels: approved, lgtm

#296 Bump mariadb-operator version
  config/rbac/role.yaml
  controllers/neutronapi_controller.go
  go.mod
  go.sum
  test/functional/neutronapi_controller_test.go
  test/kuttl/common/assert_sample_deployment.yaml
  test/kuttl/tests/neutron_tls/01-assert.yaml
Labels: lgtm

#298 Unique LeaderElectionID
  main.go
Labels: approved

#299 fix pre-commit
  api/bases/neutron.openstack.org_neutronapis.yaml
  api/go.mod
  api/go.sum
  config/crd/bases/neutron.openstack.org_neutronapis.yaml
Labels: approved

#301 Bump golangci-lint
  .golangci.yaml
  .pre-commit-config.yaml
Labels: approved, lgtm

#302 [renovate]Remove golang constraint
  renovate.json
Labels: approved, lgtm

#308 [tlse] TLS database connection
  controllers/neutronapi_controller.go
  templates/neutronapi/config/01-neutron.conf
  templates/neutronapi/config/db-sync-config.json
  templates/neutronapi/config/neutron-api-config.json
  test/functional/base_test.go
  test/functional/neutronapi_controller_test.go
Labels: approved, lgtm
